server:
  port: 9082

management:
  endpoints:
    web:
      base-path: /actuator

module:
  ocr-service:
    sqs:
      queue-url: ""
  ap-india-http:
    sqs:
      queue-url: ""
  invoiceApi:
    baseUrl: ""
